export const FAKE_POPULARS = [
  {
    backdrop_path: "/t2rAdgjSh0WYbXzdOB5zTDqzdCI.jpg",
    first_air_date: "2022-11-02",
    genre_ids: [18],
    id: 213713,
    name: "Faltu",
    origin_country: ["IN"],
    original_language: "hi",
    original_name: "Faltu",
    overview:
      "What's in a name? Amidst the arid landscape of Rajasthan, a young woman with dreamy eyes struggles to prove her worth.",
    popularity: 2195.777,
    poster_path: "/lgyFuoXs7GvKJN0mNm7z7OMOFuZ.jpg",
    vote_average: 4.5,
    vote_count: 22,
  },
];

export const FAKE_RECOMMENDATIONS = [
  {
    adult: false,
    backdrop_path: "/3Yg9TURGv1WUlFIGOhDMLM6mOHY.jpg",
    id: 218886,
    name: "Al Aghar",
    original_language: "ar",
    original_name: "الأجهر",
    overview:
      "Falsely accused of killing his mom, a teen continues his life abroad on the run. But his return home to find his family uncovers mysterious secrets about his past.",
    poster_path: "/4SqZASKpIG28TSYvopLedhBDIn3.jpg",
    media_type: "tv",
    genre_ids: [18],
    popularity: 8.256,
    first_air_date: "2023-03-23",
    vote_average: 6.5,
    vote_count: 4,
    origin_country: ["EG"],
  },
  {
    adult: false,
    backdrop_path: "/zEj8eKk2Z3OG8zo9IjpHXSjKA3Y.jpg",
    id: 203763,
    name: "Udan Patolas",
    original_language: "hi",
    original_name: "Udan Patolas",
    overview:
      "4 small town girls try to hilariously fit in the big city. They maybe unlucky in love but their sisterhood is unbreakable.",
    poster_path: "/pB090Pg2RKr6g59FNEIp6zc7mZ7.jpg",
    media_type: "tv",
    genre_ids: [18],
    popularity: 2.867,
    first_air_date: "2022-06-10",
    vote_average: 8.5,
    vote_count: 2,
    origin_country: ["IN"],
  },
  {
    adult: false,
    backdrop_path: "/z7z6zTfEeasEov6Y2ezVOxW5tsb.jpg",
    id: 100088,
    name: "The Last of Us",
    original_language: "en",
    original_name: "The Last of Us",
    overview:
      "Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone. What starts as a small job soon becomes a brutal, heartbreaking journey, as they both must traverse the United States and depend on each other for survival.",
    poster_path: "/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
    media_type: "tv",
    genre_ids: [18],
    popularity: 543.143,
    first_air_date: "2023-01-15",
    vote_average: 8.743,
    vote_count: 3411,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/caGVr9Il2gj8bN4ow6qsLm60TxM.jpg",
    id: 1416,
    name: "Grey's Anatomy",
    original_language: "en",
    original_name: "Grey's Anatomy",
    overview:
      "Follows the personal and professional lives of a group of doctors at Seattle’s Grey Sloan Memorial Hospital.",
    poster_path: "/daSFbrt8QCXV2hSwB0hqYjbj681.jpg",
    media_type: "tv",
    genre_ids: [18],
    popularity: 519.884,
    first_air_date: "2005-03-27",
    vote_average: 8.258,
    vote_count: 9155,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/azWBrlovNOOdy0eQYEe9BoiROoN.jpg",
    id: 209085,
    name: "Amor Perfeito",
    original_language: "pt",
    original_name: "Amor Perfeito",
    overview: "",
    poster_path: "/aOPhyvHDauWFuc3rthpHArCNyrm.jpg",
    media_type: "tv",
    genre_ids: [18, 10766],
    popularity: 39.508,
    first_air_date: "2023-03-20",
    vote_average: 4.8,
    vote_count: 5,
    origin_country: ["BR"],
  },
  {
    adult: false,
    backdrop_path: "/zrMCOQnzIgGyBtGCdMPom9bOw0r.jpg",
    id: 62286,
    name: "Fear the Walking Dead",
    original_language: "en",
    original_name: "Fear the Walking Dead",
    overview:
      'What did the world look like as it was transforming into the horrifying apocalypse depicted in "The Walking Dead"? This spin-off set in Los Angeles, following new characters as they face the beginning of the end of the world, will answer that question.',
    poster_path: "/zyshFjmlDXSzfns2Qk81cfIFfPP.jpg",
    media_type: "tv",
    genre_ids: [10759, 18],
    popularity: 191.739,
    first_air_date: "2015-08-23",
    vote_average: 7.691,
    vote_count: 4445,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/mt3SRKq7uRBKVntaBg2ofsDfOdg.jpg",
    id: 4629,
    name: "Stargate SG-1",
    original_language: "en",
    original_name: "Stargate SG-1",
    overview:
      "The story of Stargate SG-1 begins about a year after the events of the feature film, when the United States government learns that an ancient alien device called the Stargate can access a network of such devices on a multitude of planets. SG-1 is an elite Air Force special operations team, one of more than two dozen teams from Earth who explore the galaxy and defend against alien threats such as the Goa'uld, Replicators, and the Ori.",
    poster_path: "/rst5xc4f7v1KiDiQjzDiZqLtBpl.jpg",
    media_type: "tv",
    genre_ids: [10765, 10759, 9648],
    popularity: 190.124,
    first_air_date: "1997-07-27",
    vote_average: 8.256,
    vote_count: 1293,
    origin_country: ["CA", "US"],
  },
  {
    adult: false,
    backdrop_path: "/he4mtQe9KWsXpScDf3seER8Pkq6.jpg",
    id: 105248,
    name: "Cyberpunk: Edgerunners",
    original_language: "ja",
    original_name: "サイバーパンク：エッジランナーズ",
    overview:
      "In a dystopia riddled with corruption and cybernetic implants, a talented but reckless street kid strives to become a mercenary outlaw — an edgerunner.",
    poster_path: "/7jSWOc6jWSw5hZ78HB8Hw3pJxuk.jpg",
    media_type: "tv",
    genre_ids: [10759, 16, 10765],
    popularity: 47.438,
    first_air_date: "2022-09-13",
    vote_average: 8.612,
    vote_count: 864,
    origin_country: ["JP"],
  },
  {
    adult: false,
    backdrop_path: "/cEcjyE8UwVdnneTmbqDvRhlY6Np.jpg",
    id: 213044,
    name: "LUPIN ZERO",
    original_language: "ja",
    original_name: "LUPIN ZERO",
    overview:
      "The childhood adventures of Arsène Lupin III, set in the early 1960s before he achieved global infamy.",
    poster_path: "/zbUyE5Lc70yi88LHalRM7KFj89a.jpg",
    media_type: "tv",
    genre_ids: [16, 9648, 80, 10759],
    popularity: 7.99,
    first_air_date: "2022-12-16",
    vote_average: 7.9,
    vote_count: 7,
    origin_country: ["JP"],
  },
  {
    adult: false,
    backdrop_path: "/nWfpVLgioDXQsAbfL6UJxYz6d3d.jpg",
    id: 16997,
    name: "The Pacific",
    original_language: "en",
    original_name: "The Pacific",
    overview:
      "Track the intertwined real-life stories of three U.S. Marines – Robert Leckie, John Basilone, and Eugene Sledge – across the vast canvas of the Pacific Theater during World War II. A companion piece to the 2001 miniseries Band of Brothers.",
    poster_path: "/x9Y1IMFdY8Ma222KcQadFEau0EB.jpg",
    media_type: "tv",
    genre_ids: [18, 10759, 10768],
    popularity: 42.146,
    first_air_date: "2010-03-14",
    vote_average: 7.73,
    vote_count: 2062,
    origin_country: ["US"],
  },
];
